runtime: python39
instance_class: F2

handlers:
  - url: /index
    upload: static/index.html
    static_dir: static

  - url: /project
    upload: static/projects.html
    static_dir: static
