runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: path/to/css

- url: /js
  static_dir: path/to/js

- url: /images
  static_dir: path/to/images

- url: /.*
  script: main.py

