runtime: python39
instance_class: F2

handlers:
  - url: index.html
    upload: static/index.html
    static_dir: static

  - url: projects.html
    upload: static/projects.html
    static_dir: static
