runtime: python39
instance_class: F2

handlers:
  - url: /index
    static_files: index.html
    upload: index.html

  - url: /projects
    static_files: projects.html
    upload: projects.html

  - url: /resume
    static_file: resume.html
    upload: resume.html
